name: monitoring_kalori
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  get: 4.6.5
  hexcolor: ^2.0.7
  email_validator: ^2.1.17
  firebase_core: 1.20.1
  firebase_auth: 3.6.3
  select_form_field: 2.2.0
  cloud_firestore: 3.4.5
  material_dialogs: 1.1.3
  flutter:
    sdk: flutter

dependency_overrides:
  firebase_messaging_platform_interface:
  firebase_crashlytics_platform_interface:
  cloud_firestore_platform_interface:
  firebase_auth_platform_interface:
  firebase_storage_platform_interface:
  cloud_functions_platform_interface:
  firebase_analytics_platform_interface:
  firebase_remote_config_platform_interface:
  firebase_dynamic_links_platform_interface:
  firebase_performance_platform_interface:
  firebase_app_installations_platform_interface:

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/images/
  uses-material-design: true
